# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Build file .ipa for develop"
  lane :build_develop do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Build file .ipa for staging"
  lane :build_staging do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Build file .ipa for production"
  lane :build_production do
    # add actions here: https://docs.fastlane.tools/actions
  end
end


desc "Import certificate & install provisioning profile"
lane :setup_codesigning do
  create_keychain(
    name: "KeychainName",
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: true
  )

  install_provisioning_profile(path: "profiles/profile.mobileprovision")

  import_certificate(
    certificate_path: "certs/dist.p12",
    certificate_password: "***",
    keychain_password: "***",
    keychain_name: "KeychainName"
  )
end

desc "Build file .ipa"
private_lane :build_app do
  
  # add actions here: https://docs.fastlane.tools/actions
  build_app(
    scheme: "actionstest",
    project: ENV["XCODE_PROJ"],
  )

end

desc "Deploy to Firebase Distribution"
private_lane :deploy_firebase do
  firebase_app_distribution(
    app: "1:123456789:ios:abcd1234",
    firebase_cli_token: "",
    testers: "tester1@company.com, tester2@company.com",
    release_notes: "Lots of amazing new features to test out!",
    firebase_cli_path: "/absolute/path/to/firebase/cli/binary",
    ipa_path: ""
  )
end

desc "Increment version"
private_lane :increment_version do
  latest_release = firebase_app_distribution_get_latest_release(
    app: "<your Firebase app ID>"
  )
  increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })
end