name: Analyze pull request
on:
  pull_request:

jobs:
  Analyze:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'
          channel: 'stable'
      - run: flutter --version
