name: Build & Deploy Dev

# on:
#   push:
#     branches:
#       - 'develop'
on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_ios:
    name: Deploying
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          channel: 'stable'
          architecture: x64
      - run: flutter pub get

  build_android:
    name: Deploying
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      # - uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: '3.0.0'
      #     channel: 'stable'
      #     architecture: x64
      # - run: flutter pub get
      # - name: Build app
      #   run: flutter build apk --flavor development -t lib/main_development.dart
      # - name: Create Firebase Service Credentials file
      #   run: |
      #     echo "$FIREBASE_CREDENTIALS" > firebase_credentials.json.b64
      #     base64 -d -i firebase_credentials.json.b64 > firebase_credentials.json
      #   env:
      #     FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      # - name: Add environment variables
      #   run: export FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
      # - name: Distribute app with 🔥 App Distribution 🚀
      #   run: bundle exec fastlane development
